/* eslint-disable */
import {
  CollectionCustomizer,
  TAggregation,
  TConditionTree,
  TPaginatedFilter,
  TPartialRow,
  TSortClause
} from '@forestadmin/agent';

export type ProfilesCustomizer = CollectionCustomizer<Schema, 'profiles'>;
export type ProfilesRecord = TPartialRow<Schema, 'profiles'>;
export type ProfilesConditionTree = TConditionTree<Schema, 'profiles'>;
export type ProfilesFilter = TPaginatedFilter<Schema, 'profiles'>;
export type ProfilesSortClause = TSortClause<Schema, 'profiles'>;
export type ProfilesAggregation = TAggregation<Schema, 'profiles'>;

export type VehiclesCustomizer = CollectionCustomizer<Schema, 'vehicles'>;
export type VehiclesRecord = TPartialRow<Schema, 'vehicles'>;
export type VehiclesConditionTree = TConditionTree<Schema, 'vehicles'>;
export type VehiclesFilter = TPaginatedFilter<Schema, 'vehicles'>;
export type VehiclesSortClause = TSortClause<Schema, 'vehicles'>;
export type VehiclesAggregation = TAggregation<Schema, 'vehicles'>;

export type VehiclesPropertiesCustomizer = CollectionCustomizer<Schema, 'vehicles_properties'>;
export type VehiclesPropertiesRecord = TPartialRow<Schema, 'vehicles_properties'>;
export type VehiclesPropertiesConditionTree = TConditionTree<Schema, 'vehicles_properties'>;
export type VehiclesPropertiesFilter = TPaginatedFilter<Schema, 'vehicles_properties'>;
export type VehiclesPropertiesSortClause = TSortClause<Schema, 'vehicles_properties'>;
export type VehiclesPropertiesAggregation = TAggregation<Schema, 'vehicles_properties'>;

export type CompaniesCustomizer = CollectionCustomizer<Schema, 'companies'>;
export type CompaniesRecord = TPartialRow<Schema, 'companies'>;
export type CompaniesConditionTree = TConditionTree<Schema, 'companies'>;
export type CompaniesFilter = TPaginatedFilter<Schema, 'companies'>;
export type CompaniesSortClause = TSortClause<Schema, 'companies'>;
export type CompaniesAggregation = TAggregation<Schema, 'companies'>;

export type UsersCustomizer = CollectionCustomizer<Schema, 'users'>;
export type UsersRecord = TPartialRow<Schema, 'users'>;
export type UsersConditionTree = TConditionTree<Schema, 'users'>;
export type UsersFilter = TPaginatedFilter<Schema, 'users'>;
export type UsersSortClause = TSortClause<Schema, 'users'>;
export type UsersAggregation = TAggregation<Schema, 'users'>;


export type Schema = {
  'companies': {
    plain: {
      'id': number;
      'name': string;
      'industry': string;
      'size': number;
      'created_at': string;
      'updated_at': string;
      'user_id': number;
    };
    nested: {
      'user': Schema['users']['plain'] & Schema['users']['nested'];
    };
    flat: {
      'user:id': number;
      'user:firstname': string;
      'user:lastname': string;
      'user:email': string;
      'user:password': string;
      'user:avatar': string;
      'user:role': 'user' | 'editor' | 'admin';
      'user:status': 'enabled' | 'disabled' | 'deleted';
      'user:company_id': number;
      'user:created_at': string;
      'user:updated_at': string;
      'user:completed_at': string;
      'user:company:id': number;
      'user:company:name': string;
      'user:company:industry': string;
      'user:company:size': number;
      'user:company:created_at': string;
      'user:company:updated_at': string;
      'user:company:user_id': number;
      'user:company:user:id': number;
      'user:company:user:firstname': string;
      'user:company:user:lastname': string;
      'user:company:user:email': string;
      'user:company:user:password': string;
      'user:company:user:avatar': string;
      'user:company:user:role': 'user' | 'editor' | 'admin';
      'user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'user:company:user:company_id': number;
      'user:company:user:created_at': string;
      'user:company:user:updated_at': string;
      'user:company:user:completed_at': string;
      'user:company:user:company:id': number;
      'user:company:user:company:name': string;
      'user:company:user:company:industry': string;
      'user:company:user:company:size': number;
      'user:company:user:company:created_at': string;
      'user:company:user:company:updated_at': string;
      'user:company:user:company:user_id': number;
      'user:company:user:company:user:id': number;
      'user:company:user:company:user:firstname': string;
      'user:company:user:company:user:lastname': string;
      'user:company:user:company:user:email': string;
      'user:company:user:company:user:password': string;
      'user:company:user:company:user:avatar': string;
      'user:company:user:company:user:role': 'user' | 'editor' | 'admin';
      'user:company:user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'user:company:user:company:user:company_id': number;
      'user:company:user:company:user:created_at': string;
      'user:company:user:company:user:updated_at': string;
      'user:company:user:company:user:completed_at': string;
    };
  };
  'profiles': {
    plain: {
      'database': {signup_date: string; is_blocked: boolean};
      'contact': {cellphone: string};
      'user_id': number;
      '_id': string;
      'identity@@@address@@@city': string;
      'identity@@@address@@@country': string;
      'identity@@@address@@@number': number;
      'identity@@@address@@@street': string;
      'identity@@@address@@@zip_code': string;
      'identity@@@birthdate': string;
    };
    nested: {
      'user': Schema['users']['plain'] & Schema['users']['nested'];
    };
    flat: {
      'user:id': number;
      'user:firstname': string;
      'user:lastname': string;
      'user:email': string;
      'user:password': string;
      'user:avatar': string;
      'user:role': 'user' | 'editor' | 'admin';
      'user:status': 'enabled' | 'disabled' | 'deleted';
      'user:company_id': number;
      'user:created_at': string;
      'user:updated_at': string;
      'user:completed_at': string;
      'user:company:id': number;
      'user:company:name': string;
      'user:company:industry': string;
      'user:company:size': number;
      'user:company:created_at': string;
      'user:company:updated_at': string;
      'user:company:user_id': number;
      'user:company:user:id': number;
      'user:company:user:firstname': string;
      'user:company:user:lastname': string;
      'user:company:user:email': string;
      'user:company:user:password': string;
      'user:company:user:avatar': string;
      'user:company:user:role': 'user' | 'editor' | 'admin';
      'user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'user:company:user:company_id': number;
      'user:company:user:created_at': string;
      'user:company:user:updated_at': string;
      'user:company:user:completed_at': string;
      'user:company:user:company:id': number;
      'user:company:user:company:name': string;
      'user:company:user:company:industry': string;
      'user:company:user:company:size': number;
      'user:company:user:company:created_at': string;
      'user:company:user:company:updated_at': string;
      'user:company:user:company:user_id': number;
      'user:company:user:company:user:id': number;
      'user:company:user:company:user:firstname': string;
      'user:company:user:company:user:lastname': string;
      'user:company:user:company:user:email': string;
      'user:company:user:company:user:password': string;
      'user:company:user:company:user:avatar': string;
      'user:company:user:company:user:role': 'user' | 'editor' | 'admin';
      'user:company:user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'user:company:user:company:user:company_id': number;
      'user:company:user:company:user:created_at': string;
      'user:company:user:company:user:updated_at': string;
      'user:company:user:company:user:completed_at': string;
    };
  };
  'users': {
    plain: {
      'id': number;
      'firstname': string;
      'lastname': string;
      'email': string;
      'password': string;
      'avatar': string;
      'role': 'user' | 'editor' | 'admin';
      'status': 'enabled' | 'disabled' | 'deleted';
      'company_id': number;
      'created_at': string;
      'updated_at': string;
      'completed_at': string;
    };
    nested: {
      'company': Schema['companies']['plain'] & Schema['companies']['nested'];
    };
    flat: {
      'company:id': number;
      'company:name': string;
      'company:industry': string;
      'company:size': number;
      'company:created_at': string;
      'company:updated_at': string;
      'company:user_id': number;
      'company:user:id': number;
      'company:user:firstname': string;
      'company:user:lastname': string;
      'company:user:email': string;
      'company:user:password': string;
      'company:user:avatar': string;
      'company:user:role': 'user' | 'editor' | 'admin';
      'company:user:status': 'enabled' | 'disabled' | 'deleted';
      'company:user:company_id': number;
      'company:user:created_at': string;
      'company:user:updated_at': string;
      'company:user:completed_at': string;
      'company:user:company:id': number;
      'company:user:company:name': string;
      'company:user:company:industry': string;
      'company:user:company:size': number;
      'company:user:company:created_at': string;
      'company:user:company:updated_at': string;
      'company:user:company:user_id': number;
      'company:user:company:user:id': number;
      'company:user:company:user:firstname': string;
      'company:user:company:user:lastname': string;
      'company:user:company:user:email': string;
      'company:user:company:user:password': string;
      'company:user:company:user:avatar': string;
      'company:user:company:user:role': 'user' | 'editor' | 'admin';
      'company:user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'company:user:company:user:company_id': number;
      'company:user:company:user:created_at': string;
      'company:user:company:user:updated_at': string;
      'company:user:company:user:completed_at': string;
      'company:user:company:user:company:id': number;
      'company:user:company:user:company:name': string;
      'company:user:company:user:company:industry': string;
      'company:user:company:user:company:size': number;
      'company:user:company:user:company:created_at': string;
      'company:user:company:user:company:updated_at': string;
      'company:user:company:user:company:user_id': number;
    };
  };
  'vehicles': {
    plain: {
      'owner_id': number;
      'database': {registration_date: string; is_blocked: boolean};
      '_id': string;
      'identity@@@document@@@url': string;
      'identity@@@vin': string;
      'identity@@@vrm': string;
    };
    nested: {
      'properties': Schema['vehicles_properties']['plain'] & Schema['vehicles_properties']['nested'];
      'user': Schema['users']['plain'] & Schema['users']['nested'];
    };
    flat: {
      'properties:color': string;
      'properties:manufacturer': string;
      'properties:model': string;
      'properties:vc_type': string;
      'properties:engine': {fuel: string; power: string; as400: {model: string; variant: string}};
      'properties:_id': string;
      'properties:parentId': string;
      'user:id': number;
      'user:firstname': string;
      'user:lastname': string;
      'user:email': string;
      'user:password': string;
      'user:avatar': string;
      'user:role': 'user' | 'editor' | 'admin';
      'user:status': 'enabled' | 'disabled' | 'deleted';
      'user:company_id': number;
      'user:created_at': string;
      'user:updated_at': string;
      'user:completed_at': string;
      'user:company:id': number;
      'user:company:name': string;
      'user:company:industry': string;
      'user:company:size': number;
      'user:company:created_at': string;
      'user:company:updated_at': string;
      'user:company:user_id': number;
      'user:company:user:id': number;
      'user:company:user:firstname': string;
      'user:company:user:lastname': string;
      'user:company:user:email': string;
      'user:company:user:password': string;
      'user:company:user:avatar': string;
      'user:company:user:role': 'user' | 'editor' | 'admin';
      'user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'user:company:user:company_id': number;
      'user:company:user:created_at': string;
      'user:company:user:updated_at': string;
      'user:company:user:completed_at': string;
      'user:company:user:company:id': number;
      'user:company:user:company:name': string;
      'user:company:user:company:industry': string;
      'user:company:user:company:size': number;
      'user:company:user:company:created_at': string;
      'user:company:user:company:updated_at': string;
      'user:company:user:company:user_id': number;
      'user:company:user:company:user:id': number;
      'user:company:user:company:user:firstname': string;
      'user:company:user:company:user:lastname': string;
      'user:company:user:company:user:email': string;
      'user:company:user:company:user:password': string;
      'user:company:user:company:user:avatar': string;
      'user:company:user:company:user:role': 'user' | 'editor' | 'admin';
      'user:company:user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'user:company:user:company:user:company_id': number;
      'user:company:user:company:user:created_at': string;
      'user:company:user:company:user:updated_at': string;
      'user:company:user:company:user:completed_at': string;
    };
  };
  'vehicles_properties': {
    plain: {
      'color': string;
      'manufacturer': string;
      'model': string;
      'vc_type': string;
      'engine': {fuel: string; power: string; as400: {model: string; variant: string}};
      '_id': string;
      'parentId': string;
    };
    nested: {
      'parent': Schema['vehicles']['plain'] & Schema['vehicles']['nested'];
    };
    flat: {
      'parent:owner_id': number;
      'parent:database': {registration_date: string; is_blocked: boolean};
      'parent:_id': string;
      'parent:identity@@@document@@@url': string;
      'parent:identity@@@vin': string;
      'parent:identity@@@vrm': string;
      'parent:user:id': number;
      'parent:user:firstname': string;
      'parent:user:lastname': string;
      'parent:user:email': string;
      'parent:user:password': string;
      'parent:user:avatar': string;
      'parent:user:role': 'user' | 'editor' | 'admin';
      'parent:user:status': 'enabled' | 'disabled' | 'deleted';
      'parent:user:company_id': number;
      'parent:user:created_at': string;
      'parent:user:updated_at': string;
      'parent:user:completed_at': string;
      'parent:user:company:id': number;
      'parent:user:company:name': string;
      'parent:user:company:industry': string;
      'parent:user:company:size': number;
      'parent:user:company:created_at': string;
      'parent:user:company:updated_at': string;
      'parent:user:company:user_id': number;
      'parent:user:company:user:id': number;
      'parent:user:company:user:firstname': string;
      'parent:user:company:user:lastname': string;
      'parent:user:company:user:email': string;
      'parent:user:company:user:password': string;
      'parent:user:company:user:avatar': string;
      'parent:user:company:user:role': 'user' | 'editor' | 'admin';
      'parent:user:company:user:status': 'enabled' | 'disabled' | 'deleted';
      'parent:user:company:user:company_id': number;
      'parent:user:company:user:created_at': string;
      'parent:user:company:user:updated_at': string;
      'parent:user:company:user:completed_at': string;
      'parent:user:company:user:company:id': number;
      'parent:user:company:user:company:name': string;
      'parent:user:company:user:company:industry': string;
      'parent:user:company:user:company:size': number;
      'parent:user:company:user:company:created_at': string;
      'parent:user:company:user:company:updated_at': string;
      'parent:user:company:user:company:user_id': number;
    };
  };
};
